### ISSUE TITLE
[exception] running multiple times

### ISSUE THREAD

**Issue by ericson-cepeda** [ericson-cepeda/tests-to-doc#2]
git.exc.GitCommandError: 'git remote add bitbucket_remote git@bitbucket.org:picorb/alse.git' returned with exit code 128
stderr: 'fatal: remote bitbucket_remote already exists.'

It happens when I try to run the script multiple times, given that remote bitbucket_remote already existed.

**Comment by ericson-cepeda** [comment]
@Ignusmart check_git_repos git:(master) ✗ python script.py -path /home/ecepeda/test -owner picorb
/home/ecepeda/virtualenvs/fabric-locust/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/ecepeda/virtualenvs/fabric-locust/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "script.py", line 113, in <module>
    status = main(sys.argv[1:])
  File "script.py", line 109, in main
    check_git_repos(cmdargs)
  File "script.py", line 94, in check_git_repos
    g.execute(["git", "push", "bitbucket_remote", "--all"])
  File "/home/ecepeda/virtualenvs/fabric-locust/local/lib/python2.7/site-packages/git/cmd.py", line 702, in execute
    raise GitCommandError(command, status, stderr_value)
git.exc.GitCommandError: 'git push bitbucket_remote --all' returned with exit code 128
stderr: 'conq: repository does not exist.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.'
